version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps): update dependency"
    labels:
      - "dependencies"
      - "github-actions"
